---
# kubernetes/base/deployment.yml

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "meet-prosody-deployment"
  labels:
    app.kubernetes.io/name: "meet-prosody-deployment"
    app.kubernetes.io/component: "prosody"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "prosody"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "prosody"
    spec:
      containers:
        - name: "prosody"
          image: "jitsi/prosody:stable-6826"
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: "PUBLIC_URL"
              value: "https://meet.home.while-true-do.io"
            - name: "XMPP_DOMAIN"
              value: "meet.jitsi"
            - name: "XMPP_AUTH_DOMAIN"
              value: "auth.meet.jitsi"
            - name: "XMPP_MUC_DOMAIN"
              value: "muc.meet.jitsi"
            - name: "XMPP_INTERNAL_MUC_DOMAIN"
              value: "internal-muc.meet.jitsi"
            - name: "JICOFO_COMPONENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: "jitsi-config"
                  key: "JICOFO_COMPONENT_SECRET"
            - name: "JVB_AUTH_USER"
              value: "jvb"
            - name: "JVB_AUTH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "jitsi-config"
                  key: "JVB_AUTH_PASSWORD"
            - name: "JICOFO_AUTH_USER"
              value: "focus"
            - name: "JICOFO_AUTH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "jitsi-config"
                  key: "JICOFO_AUTH_PASSWORD"
            - name: "TZ"
              value: "UTC"
            - name: "JVB_TCP_HARVESTER_DISABLED"
              value: "true"
          ports:
            - containerPort: 5222
            - containerPort: 5347
            - containerPort: 5280
...
