---
# kubernetes/base/deployment.yml

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "meet-jvb-deployment"
  labels:
    app.kubernetes.io/name: "meet-jvb-deployment"
    app.kubernetes.io/component: "jvb"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "jvb"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "jvb"
    spec:
      containers:
        - name: "jvb"
          image: "jitsi/jvb:stable-6826"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "250m"
          env:
            - name: XMPP_SERVER
              value: meet-prosody-service
            - name: DOCKER_HOST_ADDRESS
              value: meet-prosody-service
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "30300"
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "jitsi-config"
                  key: "JVB_AUTH_PASSWORD"
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "jitsi-config"
                  key: "JICOFO_AUTH_PASSWORD"
            - name: "JVB_BREWERY_MUC"
              value: "jvbbrewery"
            - name: "TZ"
              value: "UTC"
          ports:
            - containerPort: 30300
              protocol: "UDP"
            - containerPort: 8080
...
