---
# kubernetes/base/service.yml

apiVersion: "v1"
kind: "Service"
metadata:
  name: "meet-web-service"
  labels:
    app.kubernetes.io/name: "meet-web-service"
    app.kubernetes.io/component: "web"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/component: "web"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 80
    - name: "https"
      protocol: "TCP"
      port: 443
      targetPort: 443
...
